version: '3.4'

services:
  freshmanragbot:
    image: freshmanragbot
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - postgres-network
    volumes:
      - ${PWD}/.models/:/app/.models
  db:
    image: pgvector/pgvector:pg16
    restart: always
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - postgres-network
    volumes:
      - ${PWD}/pgadmin-data/:/var/lib/pgadmin/

networks:
  postgres-network:
    driver: bridge
