rag_prompt:
  _target_: langchain_core.prompts.PromptTemplate.from_template
  template: >
    <start_of_turn>user
    Ви - асистент у завданнях з відповідями на запитання. Використовуйте наведений нижче контекст, щоб відповісти на запитання, що стосуються першокурсників. Якщо ви не знаєте відповіді, просто скажіть, що не знаєте. Відповідайте стисло.
    Відповідай виключно українською.

    Запитання: {question}

    Контекст: {context}<end_of_turn>
    <start_of_turn>model
    Відповідь:
grading_prompt:
  _target_: langchain_core.prompts.PromptTemplate.from_template
  template: >
    <start_of_turn>user
    Ви - система, яка оцінює відповідність питання до наданих фактів.

    Ви оцінюєте відповідність факту до питання:
    Оцінка 1 означає, що БУДЬ-ЯКЕ з тверджень у ФАКТІ має хоч якесь відношення до ЗАПИТАННЯ.
    Оцінка 0 означає, що ЖОДНЕ з тверджень у ФАКТІ не має відношення до ЗАПИТАННЯ.
    1 - найвищий (найкращий) бал. 0 - найнижчий бал, який Ви можете поставити.

    Факт не повинен повністю відповідати на питання, простого визначення достатньо.
    Факт може просто бути синонімом чи стверджувати, що об'єкт з питання є чимось.
    Якщо ви не певні / точно не знаєте, то відповідай, що факт відповідає питанню.

    Поясніть свої міркування поетапно. Переконайтеся, що ваші міркування та висновки є правильними.

    Уникайте простого зазначення правильної відповіді на початку.

    ЗАПИТАННЯ: {question}

    ФАКТ:

    {document}


    Дайте бінарну оцінку, щоб вказати, чи відповідає документ запитанню. Надайте бінарну оцінку у форматі JSON з єдиним ключовим словом "score" без оцінки чи пояснень.<end_of_turn>
    <start_of_turn>model
rewriting_prompt:
  _target_: langchain_core.prompts.PromptTemplate.from_template
  template: >
    <start_of_turn>user
    Перепишіть дане питання для системи пошуку, щоб максимізувати шанс надати точну відповідь на поставлене запитання.
    Відповідай стисло, кількість речень не повинна набагато перевищувати кількість речень у оригінальному питанні.
    Додай у згенероване питання ключові слова з оригінального питання. Відповідай ВИКЛЮЧНО українською мовою.

    Деякі синоніми через тире згруповані за темами, які можуть бути (але не обов'язково) у нагоді:

    Спеціальність Прикладна математика: прикладна математика - 113 (код спеціальності) - примат (людина) - ми - ви - у нас

    Освітня програма "Математичні методи криптографічного захисту інформації": ММЗІ (кафедра) - крипта (скорочено від криптологія) - ФІ-x3 (назва групи) - криптологи (люди)

    Освітня програма "Математичні методи моделювання, розпізнавання образів та комп’ютерного зору": ММАД (кафедра) - матмод - РОКЗ - ФІ-x1 (назва групи)

    Спеціальність Кібербезпека: 125 (код спеціальності) - кіббези (люди) - ФБ - ФЕ - ФБшники (люди)

    Фізіко-технічний інститут: ФТІ - фізтех - НН ФТІ

    Додаткова сессія: допка - додаткова сессія - коміссія - не склав - завалив предмет - єшка

    Обов'язково використай ці синоніми, якщо у питанні є якесь з пов'язаних слів й ігноруй, якщо нема.
    Питання не повинно змінювати суть, змінюй ЛИШЕ форму питання не додавай нічого нового. Не відповідай самостійно на запитання.
    Запитання: {question}<end_of_turn>
    <start_of_turn>model
    Відповідь: