_target_: crag.knoweledge.transformations.sequence.TransformationSequence
transforms:
  -
    - text_splitter
    - _target_: langchain_text_splitters.RecursiveCharacterTextSplitter.from_tiktoken_encoder
      chunk_size: 2000
      chunk_overlap: 0
