defaults:
  - _self_
  - retriever: pgvector
  - llm: gemma2_2b_it
  - prompts: gemma2
  - pipeline: rag_with_question_rewriting

bot_db_connection: "postgresql+psycopg://${oc.env:POSTGRES_USER}:${oc.env:POSTGRES_PASSWORD}@${oc.env:POSTGRES_HOST}:5432/${oc.env:POSTGRES_DB}"